# Generated by Django 6.0.7 on 2026-08-01 15:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_activity_options_alter_event_options_and_more'),
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venue',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='venue',
            name='activities',
            field=models.ManyToManyField(blank=True, help_text='Sports available at this venue.', related_name='venues', to='events.activity'),
        ),
        migrations.AddField(
            model_name='venue',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='venue_images/'),
        ),
        migrations.AddField(
            model_name='venue',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='venue',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='duration_label',
            field=models.CharField(blank=True, default='1 Hour', max_length=50),
        ),
        migrations.AddField(
            model_name='venue',
            name='equipment_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='has_floodlights',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='has_parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='has_seating_lounge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='has_washroom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='has_wifi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.CreateModel(
            name='VenueImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='venue_images/gallery/')),
                ('caption', models.CharField(blank=True, max_length=150)),
                ('order', models.PositiveIntegerField(default=0)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='venues.venue')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
