# Generated by Django 6.0.7 on 2026-08-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0003_court_courtbooking_venuefavourite_venuereview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='has_cafe',
            field=models.BooleanField(default=False),
        ),
    ]
