# Generated by Django 6.0.7 on 2026-08-11 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0004_venue_has_cafe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='has_cafe',
        ),
    ]
