# Generated by Django 6.0.7 on 2026-08-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0005_remove_venue_has_cafe'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='has_showers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='live_match_now',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
