# Generated by Django 6.0.7 on 2026-08-11 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_activity_options_alter_event_options_and_more'),
        ('venues', '0006_venue_has_showers_venue_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.activity'),
        ),
        migrations.AddField(
            model_name='court',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='court',
            name='peak_end_hour',
            field=models.IntegerField(default=21),
        ),
        migrations.AddField(
            model_name='court',
            name='peak_start_hour',
            field=models.IntegerField(default=18),
        ),
    ]
