# Generated by Django 6.0.7 on 2026-08-13 16:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0007_court_activity_court_order_court_peak_end_hour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courtbooking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
