# Generated by Django 6.0.7 on 2026-07-12 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('price_per_slot', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_slots', models.PositiveIntegerField()),
                ('status', models.CharField(default='upcoming', max_length=20)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.activity')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='venues.venue')),
            ],
        ),
    ]
