# Generated by Django 6.0.7 on 2026-07-19 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_addon_alter_booking_options_and_more'),
        ('bookings', '0002_alter_booking_event'),
    ]

    operations = [
    ]
